### ISSUE TITLE
BASE_URL

### ISSUE THREAD

**Issue by UsmanKhan15** [pisegov/white-dragon-vpn#1]
what is To run the project, you need to place the backend address in local.properties in the form BASE_URL = YOUR_URL? how to set this?

**Comment by pisegov** [comment]
> what is To run the project, you need to place the backend address in local.properties in the form BASE_URL = YOUR_URL? how to set this?

1. Clone the project
2. Open it in android studio. It should create a "local.properties" file automatically
3. Put the following line at the end of "local.properties"
```
BASE_URL="https://yourhost.com/"
```

Note that you need to implement your own backend server to make this application work
As an example, you can check this repo: https://github.com/pisegov/white-dragon-wg-server
